# data_path: /home/nburgdor/data/DTU/
# output_path: /home/nburgdor/Results/DTU/ABNet/
data_path: /mnt/Drive2/DTU/
output_path: /mnt/Drive1/Results/DTU/ABNet/
device: cuda:0
seed: 43
num_workers: 4

camera:
    height: 1200
    width: 1600
    near: 425
    far: 937
    divisible_factor: 64
    baseline_mode: max

inference:
    ckpt_file: pretrained_models/model_ABNet.pt
    frame_spacing: 1
    num_frame: 5
    sample_mode: cluster
    scale: 1.0
    visualize: True
    vis_freq: 1

loss:
    weights: [1,1,1,1]
    rmse_weight: 0.01

model:
    feature_channels: [8, 16, 32, 64] # fine -> coarse
    group_channels: [4,8,8,8] # fine -> coarse
    resolution_stages: [3,3,2,2,1,1,0,0] # The resolution stages for each iteration (0 is the largest)
    stage_training: True
    stage_intervals: [2,4,6]
    z_planes: [128, 128, 64, 32, 16, 16, 16, 16]
    disparity: [1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5] 

optimizer:
    grad_clip: 1000.0
    learning_rate: 0.0001
    weight_decay: 0.01
    milestones: [10, 12, 14]
    gamma: 0.5

point_cloud:
  image_region_th: 2
  depth_region_th: 2
  pix_th: 0.50
  prob_th: 0.80
  num_consistent: 3
  mask_th: 20
  max_dist: 0.2
  min_dist: 0.0
  min_point_dist: 0.2 # use 0.2 (0.03) with sparse (dense) GT point clouds
  resolution: sparse # OPTIONS: [sparse, dense]

training:
    batch_size: 1
    ckpt_file: 
    epochs: 16
    frame_spacing: 1
    num_frame: 5
    random_crop:
        enable: True
        height: 512
        width: 640
    sample_mode: cluster
    scale: 1.0
    visualize: False
    vis_freq: 100

visualization:
    max_depth_error: 5.0
